name: Trunk Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  trunk-check:
    runs-on: ubuntu-latest
    name: Trunk Check Runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: all

  trunk-fmt:
    runs-on: ubuntu-latest
    name: Trunk Format Check
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trunk Format Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: all
          arguments: --no-fix
